packages/ui/package.json, packages/ui/src/index.d.ts
- Add TypeScript definitions for some of `@gnomad/ui` components.
- Add step to build command to copy type definition, which is in `src` to `lib`, which is the directory that will be published to npm.
=> Add TypeScript definition for @gnomad/ui

packages/classification-selector/CHANGELOG.md, packages/classification-selector/package.json, packages/classification-selector/rollup.config.js
Remove `react` and `react-dom` (both are peer dependencies) from being bundled in the build because otherwise, React will complain about having multiple copies of itself at run time in the consumer.
=> Fix Rollup build of classification selector component

packages/identifiers/src/identifiers.js, packages/identifiers/src/identifiers.spec.js
For example, recognize "m.300" as a valid position and "m.300-A-T" as a variant ID.
=> Accept "." as separator between chromosome and position

packages/classification-selector/cypress/integration/classificationViewer.spec.js, packages/classification-selector/package.json, packages/classification-selector/src/ClassificationViewer.tsx, packages/classification-selector/src/TestWrapper.tsx, packages/classification-selector/src/Utils.ts, packages/classification-selector/src/__tests__/Utils.js, packages/classification-selector/src/cypressTestDataAttrs.json, packages/classification-selector/src/index.stories.js, packages/classification-selector/src/useClassificationSelectorState.ts
Previously, categories at different levels of a hierarchical classification can only be shown by picking a numerical level from a dropdown list. This PR makes all levels of a hierarchical classification explorable through the Tree View component's expand/collapse feature.
=> Make visual view of hierarchical classifications match their structures

packages/identifiers/src/identifiers.js, packages/identifiers/src/identifiers.spec.js
Add support for additional formats for variant IDs. For example:
* m.A3243G (format frequently used for mitochondrial variants)
* m.3243A>G (similar to HGVSc format)
Also, `normalizeVariantId` now throws an error if it cannot recognize the ID. Previously, it was assumed that `normalizeVariantId` was only called with a string that passed the `isVariantId` test.
=> Recognize additional formats for variant IDs

packages/identifiers/src/identifiers.js, packages/identifiers/src/identifiers.spec.js
Previously, positions / regions without an end coordinate were converted to 40 base regions centered on the position. The previous behavior was based on how region search works in the gnomAD browser's region.
Also, similar to #20, `normalizeRegionId` now throws an error if it cannot parse a string. Previously, it was assumed that `normalizeRegionId` would only be called on strings that passed an `isRegionId` test.
=> Normalize positions to 1 base regions

packages/identifiers/src/identifiers.js, packages/identifiers/src/identifiers.spec.js
Add `parseVariantId` and `parseRegionId` functions to that return objects with components of IDs (`{ chrom, pos, ref, alt }` and `{ chrom, start, stop }`).
A common pattern in the gnomAD browser is:
```js
const normalizedVariantId = normalizeVariantId(variantId)
let [chrom, pos, ref, alt] = normalizedVariantId.split('-')
pos = Number(pos)
```
These functions would replace that pattern.
=> Add parse region ID / variant ID functions

packages/ui/CHANGELOG.md, packages/ui/src/SegmentedControl.js
Currently, when space constrained, segmented control labels may wrap onto multiple lines and overflow the control.
Before
After
=> Prevent segmented control labels from wrapping to multiple lines

packages/classification-selector/CHANGELOG.md, packages/classification-selector/cypress/integration/classificationViewer.spec.js, packages/classification-selector/package.json, packages/classification-selector/src/index.stories.js, packages/classification-selector/src/types.ts, packages/classification-selector/src/useClassificationSelectorState.ts
Previously, each item can only belong to a single category of any
classification. That restriction is now lifted so that each item can belong to multiple categories.
=> Allow each item to belong to multiple categories of a hierarchical classification

packages/classification-selector/cypress/integration/classificationViewer.spec.js, packages/classification-selector/package.json, packages/classification-selector/src/TestWrapper.tsx, packages/classification-selector/src/index.stories.js, packages/classification-selector/src/types.ts, packages/classification-selector/src/useClassificationSelectorState.ts
- Add option to automatically expand the first classification in the classification selector
- Allow items to not belong to any simple or hierarchical category and handle them appropriately.
=> Improve classification selector

packages/region-viewer/example/RegionViewerExample.js, packages/region-viewer/src/Cursor.js
The gnomAD browser uses the region viewer's Cursor component to navigate the variants table. We got some feedback that the current "window" style is misleading because clicking on the track doesn't actually show the variants contained in the window, it actually scrolls to the variants nearest the center point of the window. See screenshots in broadinstitute/gnomad-browser#583.
This adds a prop to allow changing how the cursor is rendered.
=> Add option to control how region viewer cursor is rendered

packages/classification-selector/src/ClassificationViewer.tsx
Replace Material UI's `Box` with a simple `div` to fix weird styling bug on first render in the production UKB browser. This shouldn't have any visual effect.
=> Make minor tweak to classification selector's React markup

packages/ui/src/tooltip/TooltipHint.js
A dashed underline is used to hint that a tooltip with more information is available.
Currently, the underline is close enough to the text that it interferes with legibility. This moves the underline farther away from the text and reduces its size.
Before:
After:
It also adds a print media style to hide the underline when the page is printed.
=> Adjust tooltip hint styles

packages/ui/example/TooltipExample.js, packages/ui/src/index.d.ts, packages/ui/src/tooltip/DefaultTooltip.js
Currently, the default tooltip component expects a string for tooltip content. However, since it just renders the `tooltip` prop, there's no reason why it can't accept a node as well. This updates prop types and TypeScript types accordingly.
=> Accept a node for default tooltip content

packages/ui/src/List.js
Currently, ordered lists use the same disc marker as unordered lists. This changes them to use numbers.
Resolves #9
It also removes this use of [`withComponent`](https://styled-components.com/docs/api#withcomponent), which is a "candidate for deprecation" in styled-components.
=> Change list style type for ordered list

packages/identifiers/src/identifiers.spec.js, packages/identifiers/src/identifiers.ts
Support variant IDs like 1:55516888 G/GA
Resolves #29
This also store regexes for parts of IDs (chromosome, position, allele, separator) in variables to make the overall regexes easier to understand. And uses [non-capturing groups](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges) for groups that aren't needed for the final result.
=> Accept white space and slashes as separators in region and variant IDs

packages/track-genes/example/GenesTrackExample.js, packages/track-genes/src/GenesPlot.js, packages/track-genes/src/GenesTrack.js
In the gnomAD browser, on the region page, clicking on a gene in the genes track navigates to the gene page for that gene. This is currently handled with an onClick listener on the label's `<text>` element. However, using link elements would be preferable for accessibility.
To make the genes track more flexible, this replaces GenesPlot's `onGeneClick` prop with an `renderGeneLabel` prop which allows the consumer to customize how labels are rendered.
=> Allow customizing how gene labels in genes track are rendered

packages/region-viewer/package.json, packages/region-viewer/src/RegionViewer.js, packages/region-viewer/src/Track.js, packages/region-viewer/src/coordinates.js, packages/region-viewer/src/coordinates.spec.js, yarn.lock
Ramda is a pretty heavy dependency relative to what it's used for in region-viewer. This refactors creating the `scalePosition` function used to map genomic positions to x coordinates and drops Ramda as a dependency.
Breaking changes:
- `offsetPositions` is no longer passed down to tracks. It is replaced by `regions`, which includes most of the same information except for the `offset` field on regions, which previously contained a cumulative count of how much distance was skipped between previous regions. The coverage track in gnomAD currently uses this, but its use can be replaced with `regions` and `isPositionDefined`.
- `positionOffset` is no longer passed down to tracks. For the most part, it was only useful when used with `xScale`. `scalePosition` can be used to directly map genomic …
=> Rewrite region-viewer's position scale

packages/identifiers/src/identifiers.spec.js, packages/identifiers/src/identifiers.ts
There are several hyphen/dash-like Unicode characters besides "-". This updates regexes for variant and region IDs to accept any Unicode dash character.
More information:
- https://jkorpela.fi/dashes.html
- https://javascript.info/regexp-unicode#unicode-properties-p
Related to broadinstitute/gnomad-browser#758
=> Accept Unicode dashes as separators in variant/region IDs

packages/identifiers/src/identifiers.ts
#51 added support for Unicode dashes in variant/region IDs. However, the Unicode RegExp flag is not supported in IE 11. This adds a check if that flag is supported and falls back to using "-" instead of a Unicode property if it is not supported.
Resolves #57
=> Add fallback if Unicode is not supported in regular expressions

packages/identifiers/src/identifiers.spec.js, packages/identifiers/src/identifiers.ts
=> Accept underscores and pipes as separators in variant/region IDs

.github/workflows/add-to-project.yml
dependabot PRs execute with different permissions since they originate from an external fork. This updates the action to use an event that runs in the context target repository that the PR is being created against, which should allow it to modify issues/labels/projects etc.
=> use pull_request_target

.github/dependabot.yml
Reducing the frequency of the security updates to weekly -- I've also enabled the repository's security update grouping setting, which should theoretically have it do all its updates in one PR.
=> update dependabot interval to weekly
